package tmall.pojo;

import java.math.BigDecimal;
import tmall.mapper.DetailsitemMapper;
import tmall.pojo.extension.ConfigExtension;

public class Detailsitem extends ConfigExtension implements tmall.pojo.ORM.POJOMapper<DetailsitemMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailsitem.oid
     *
     * @mbg.generated
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailsitem.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailsitem.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailsitem.sum
     *
     * @mbg.generated
     */
    private BigDecimal sum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailsitem.oid
     *
     * @return the value of detailsitem.oid
     *
     * @mbg.generated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailsitem.oid
     *
     * @param oid the value for detailsitem.oid
     *
     * @mbg.generated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailsitem.pid
     *
     * @return the value of detailsitem.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailsitem.pid
     *
     * @param pid the value for detailsitem.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailsitem.number
     *
     * @return the value of detailsitem.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailsitem.number
     *
     * @param number the value for detailsitem.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailsitem.sum
     *
     * @return the value of detailsitem.sum
     *
     * @mbg.generated
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailsitem.sum
     *
     * @param sum the value for detailsitem.sum
     *
     * @mbg.generated
     */
    public void setSum(BigDecimal sum) {
        this.sum = sum;
    }
}