package tmall.pojo;

import tmall.mapper.ServiceImageMapper;
import tmall.pojo.extension.ServiceImageExtension;

public class ServiceImage extends ServiceImageExtension implements tmall.pojo.ORM.POJOMapper<ServiceImageMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_image.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_image.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_image.pid
     *
     * @return the value of service_image.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_image.pid
     *
     * @param pid the value for service_image.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_image.type
     *
     * @return the value of service_image.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_image.type
     *
     * @param type the value for service_image.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}