package tmall.pojo;

import java.math.BigDecimal;
import java.util.Date;
import tmall.mapper.ServiceMapper;
import tmall.pojo.extension.ServiceExtension;

public class Service extends ServiceExtension implements tmall.pojo.ORM.POJOMapper<ServiceMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.subTitle
     *
     * @mbg.generated
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.imgid
     *
     * @mbg.generated
     */
    private Integer imgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.createDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.saleCount
     *
     * @mbg.generated
     */
    private Integer saleCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.cid
     *
     * @return the value of service.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.cid
     *
     * @param cid the value for service.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.name
     *
     * @return the value of service.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.name
     *
     * @param name the value for service.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.subTitle
     *
     * @return the value of service.subTitle
     *
     * @mbg.generated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.subTitle
     *
     * @param subTitle the value for service.subTitle
     *
     * @mbg.generated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.price
     *
     * @return the value of service.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.price
     *
     * @param price the value for service.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.stock
     *
     * @return the value of service.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.stock
     *
     * @param stock the value for service.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.imgid
     *
     * @return the value of service.imgid
     *
     * @mbg.generated
     */
    public Integer getImgid() {
        return imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.imgid
     *
     * @param imgid the value for service.imgid
     *
     * @mbg.generated
     */
    public void setImgid(Integer imgid) {
        this.imgid = imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.createDate
     *
     * @return the value of service.createDate
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.createDate
     *
     * @param createDate the value for service.createDate
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.saleCount
     *
     * @return the value of service.saleCount
     *
     * @mbg.generated
     */
    public Integer getSaleCount() {
        return saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.saleCount
     *
     * @param saleCount the value for service.saleCount
     *
     * @mbg.generated
     */
    public void setSaleCount(Integer saleCount) {
        this.saleCount = saleCount;
    }
}