package tmall.pojo;

import tmall.mapper.SPropertyMapper;
import tmall.pojo.extension.SPropertyExtension;

public class SProperty extends SPropertyExtension implements tmall.pojo.ORM.POJOMapper<SPropertyMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sproperty.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sproperty.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sproperty.cid
     *
     * @return the value of sproperty.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sproperty.cid
     *
     * @param cid the value for sproperty.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sproperty.name
     *
     * @return the value of sproperty.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sproperty.name
     *
     * @param name the value for sproperty.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}