package tmall.pojo;

import tmall.mapper.TypeMapper;
import tmall.pojo.extension.TypeExtension;

public class Type extends TypeExtension implements tmall.pojo.ORM.POJOMapper<TypeMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.recommend
     *
     * @mbg.generated
     */
    private Integer recommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.name
     *
     * @return the value of type.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.name
     *
     * @param name the value for type.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.recommend
     *
     * @return the value of type.recommend
     *
     * @mbg.generated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.recommend
     *
     * @param recommend the value for type.recommend
     *
     * @mbg.generated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }
}