package tmall.mapper;

import java.util.List;
import tmall.pojo.Detailsitem;
import tmall.pojo.DetailsitemExample;

public interface DetailsitemMapper extends BaseMapper<Detailsitem, DetailsitemExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailsitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailsitem
     *
     * @mbg.generated
     */
    int insert(Detailsitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailsitem
     *
     * @mbg.generated
     */
    int insertSelective(Detailsitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailsitem
     *
     * @mbg.generated
     */
    List<Detailsitem> selectByExample(DetailsitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailsitem
     *
     * @mbg.generated
     */
    Detailsitem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailsitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Detailsitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailsitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Detailsitem record);
}