package tmall.mapper;

import java.sql.Timestamp;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import tmall.pojo.Details;
import tmall.pojo.DetailsExample;

public interface DetailsMapper extends BaseMapper<Details, DetailsExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details_
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details_
     *
     * @mbg.generated
     */
    int insert(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details_
     *
     * @mbg.generated
     */
    int insertSelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details_
     *
     * @mbg.generated
     */
    List<Details> selectByExample(DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details_
     *
     * @mbg.generated
     */
    Details selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details_
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details_
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Details record);

    int update(@Param("id") int id, @Param("date") Date date);
}