package tmall.mapper;

import java.util.List;
import tmall.pojo.ServiceImage;
import tmall.pojo.ServiceImageExample;

public interface ServiceImageMapper extends BaseMapper<ServiceImage, ServiceImageExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_image
     *
     * @mbg.generated
     */
    int insert(ServiceImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_image
     *
     * @mbg.generated
     */
    int insertSelective(ServiceImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_image
     *
     * @mbg.generated
     */
    List<ServiceImage> selectByExample(ServiceImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_image
     *
     * @mbg.generated
     */
    ServiceImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServiceImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServiceImage record);
}