package tmall.mapper;

import java.util.List;
import tmall.pojo.SProperty;
import tmall.pojo.SPropertyExample;

public interface SPropertyMapper extends BaseMapper<SProperty, SPropertyExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sproperty
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sproperty
     *
     * @mbg.generated
     */
    int insert(SProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sproperty
     *
     * @mbg.generated
     */
    int insertSelective(SProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sproperty
     *
     * @mbg.generated
     */
    List<SProperty> selectByExample(SPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sproperty
     *
     * @mbg.generated
     */
    SProperty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sproperty
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sproperty
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SProperty record);
}